/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdvisorRouteImport } from './routes/_authenticated/advisor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPasswordRouteImport } from './routes/_authenticated/password'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as AuthenticatedAdminBlocksRouteImport } from './routes/_authenticated/admin.blocks'
import { Route as AuthenticatedAdminCohortsRouteImport } from './routes/_authenticated/admin.cohorts'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdvisorRoute = AuthenticatedAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasswordRoute = AuthenticatedPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlocksRoute =
  AuthenticatedAdminBlocksRouteImport.update({
    id: '/blocks',
    path: '/blocks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCohortsRoute =
  AuthenticatedAdminCohortsRouteImport.update({
    id: '/cohorts',
    path: '/cohorts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/blocks': typeof AuthenticatedAdminBlocksRoute
  '/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/advisor': typeof AuthenticatedAdvisorRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/blocks': typeof AuthenticatedAdminBlocksRoute
  '/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/advisor': typeof AuthenticatedAdvisorRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/password': typeof AuthenticatedPasswordRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/blocks': typeof AuthenticatedAdminBlocksRoute
  '/_authenticated/admin/cohorts': typeof AuthenticatedAdminCohortsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/advisor'
    | '/dashboard'
    | '/password'
    | '/admin/attendance'
    | '/admin/blocks'
    | '/admin/cohorts'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/advisor'
    | '/dashboard'
    | '/password'
    | '/admin/attendance'
    | '/admin/blocks'
    | '/admin/cohorts'
    | '/admin/reports'
    | '/admin/students'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/advisor'
    | '/_authenticated/dashboard'
    | '/_authenticated/password'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/blocks'
    | '/_authenticated/admin/cohorts'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advisor': {
      id: '/_authenticated/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AuthenticatedAdvisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/password': {
      id: '/_authenticated/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AuthenticatedPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blocks': {
      id: '/_authenticated/admin/blocks'
      path: '/blocks'
      fullPath: '/admin/blocks'
      preLoaderRoute: typeof AuthenticatedAdminBlocksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cohorts': {
      id: '/_authenticated/admin/cohorts'
      path: '/cohorts'
      fullPath: '/admin/cohorts'
      preLoaderRoute: typeof AuthenticatedAdminCohortsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminBlocksRoute: typeof AuthenticatedAdminBlocksRoute
  AuthenticatedAdminCohortsRoute: typeof AuthenticatedAdminCohortsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminBlocksRoute: AuthenticatedAdminBlocksRoute,
  AuthenticatedAdminCohortsRoute: AuthenticatedAdminCohortsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAdvisorRoute: typeof AuthenticatedAdvisorRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPasswordRoute: typeof AuthenticatedPasswordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAdvisorRoute: AuthenticatedAdvisorRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPasswordRoute: AuthenticatedPasswordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
